### ISSUE TITLE
How to cite block renders the volume and issue numbers reversed

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#1666]
**Describe the bug**
The how to cite block in the article pages shows the issue and volume number combinations as volume(issue) instead of issue(volume).
The order is correct in the citation styles section

**Janeway version**
v1.3.8

**Todo**

- [ ] Editors can select a default citation style
- [ ] The how to cite block uses the logic from the selected citation style
- [ ] The citation style can handle volume and/or issue set to zero
- [ ] The "how to cite" override at the article level has priority over the default citation style

**Comment by pgoussy** [comment]
I was just about to create a new feature request for this! The TIA editors, specifically, have been asking for the ability to set their How To Cite to more closely follow APA style.

**Comment by joemull** [comment]
An editor has asked about support for more citations styles, specifically Chicago.

**Comment by S-Haime** [comment]
(As I've been thinking about it for a while, I've put some of the citation issues here). @ajrbyers may link to your citation plugin work.

**Comment by ajrbyers** [comment]
Backlog Refinement: @mauromsl suggested we investigate the Crossref API for generating citations.

https://www.crossref.org/documentation/retrieve-metadata/xml-api/querying-with-formatted-citations/

**Comment by joemull** [comment]
## Investigation results

We'd like to avoid depending on the Crossref API if possible, since it would only work for journals that use Crossref.

So I've found a possible alternative: combine John MacFarlane's `citeproc` library via `pypandoc_binary` with CSL XML.

A proof of concept can be explored on the [`b-1666-csl-support` branch](https://github.com/openlibhums/janeway/tree/b-1666-csl-support).

**Comment by ajrbyers** [comment]
BRF: @mauromsl and @joemull to investigate this further

**Comment by pgoussy** [comment]
FYI, we just got another new journal (the Journal of Glass Studies, `JGS`) asking if they could change their "How to Cite" to follow the Chicago Manual of Style.

**Comment by joemull** [comment]
This is the library we'd like to use: https://github.com/jgm/citeproc

**Comment by joemull** [comment]
We have now started a repository for a new a package to make the Haskell library usable in Python: https://github.com/openlibhums/citeproc-python/issues/3
