### ISSUE TITLE
Add mailgun tracking option to show status of sent emails

### ISSUE THREAD

**Issue by MartinPaulEve** [BirkbeckCTP/janeway#186]
When we send emails for peer review using mailgun, use their api to display:

* A green tick if sent fine
* An orange alert if sending is pending
* A red cross if the email wasn't delivered

**Comment by ajrbyers** [comment]
@MartinPaulEve we need to discuss whether we write our own mailgun based email setup, it would be the only way to implement this.

**Comment by ajrbyers** [comment]
- [ ] Update install_cron to add a hourly check for mailgun
- [ ] Update django mailgun to send back the email api details
- [ ] Update log entries to store mailgun message IDs
- [ ] Update transactional emails to store mailgun message IDs
- [ ] Add new management command that will query the mailgun API
